---
- hosts: External Host

  become: yes
  any_errors_fatal: true
  tasks:
    - name: Rsync Files to Server
      copy: 
        src: /etc/semaphore/checksslforjenkins.sh
        dest: /tmp/checksslforjenkins.sh
        mode: 0755

    - name: Execute script rsync all files
      command: /tmp/checksslforjenkins.sh

    - name: Remove the script
      file:
        path: /tmp/checksslforjenkins.sh
        state: absent