---
- hosts: IP

  become: yes
  any_errors_fatal: true
  tasks:
    - name: Copy the script to copy files
      copy: 
        src: /etc/semaphore/renamer.sh
        dest: /tmp/renamer.sh
        mode: 0755

    - name: Execute script rename all to correct
      command: /tmp/renamer.sh

    - name: Remove the script
      file:
        path: /tmp/renamer.sh
        state: absent