---
- name: Synchronize Git Repositories
  hosts: localhost
  gather_facts: no
  vars:
    source_repo: "GIT1 URL"
    dest_repo: "GIT2 URL"
    access_token: "{{ lookup('env', 'GIT TOKEN') }}"
    workdir: "/tmp/git_sync"

  tasks:
    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure workdir exists
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: directory
        mode: '0755'

    - name: Clone source repository
      ansible.builtin.git:
        repo: "{{ source_repo }}"
        dest: "{{ workdir }}/source"
        clone: yes
        update: yes

    - name: Initialize destination repository
      ansible.builtin.shell: |
        rm -rf {{ workdir }}/dest
        git clone https://oauth2:{{ access_token }}@github.com/DaBlubber/MyCollection.git {{ workdir }}/dest
      args:
        executable: /bin/bash

    - name: Sync files
      ansible.builtin.shell: |
        rsync -a --delete {{ workdir }}/source/ {{ workdir }}/dest/
      args:
        executable: /bin/bash

    - name: Commit and push changes
      ansible.builtin.shell: |
        cd {{ workdir }}/dest
        git config user.name "Ansible Bot"
        git config user.email "florian@nerdyadmins.de"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated sync from source repo"
        git push --force https://{{ access_token }}@github.com/DaBlubber/MyCollection.git
      args:
        executable: /bin/bash

